

cc_library(
    name = "communication",
    srcs = ["main.cpp"],
    hdrs = [
        "commMode.hpp",
        "socketCommunication.hpp",
        "iCommunication.hpp",
    ],
    deps = ["//Logger:logger"],
    visibility = ["//visibility:public"],  # Make it visible for other targets
)

